name: Release
on:
  push:
    tags: [ "v*" ]
permissions:
  contents: write   # to create release & upload assets
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout  # v4
      - uses: actions/setup-java #@<SHA> v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn -B -e -DskipTests package
      - run: mkdir -p dist && cp target/*-jar-with-dependencies.jar dist/app.jar
      - uses: softprops/action-gh-release  #@<SHA> v2
        with:
          generate_release_notes: true
          files: dist/app.jar

