name: Semgrep

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run Semgrep with the default open-source policy bundle
      - name: Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
          generateSarif: true

      # Upload results to the Security tab (no external account needed)
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
